name: Deploy Firebase

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out repository
      uses: actions/checkout@v2

    # Step 2: Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    # Step 3: Install Firebase CLI globally
    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    # Step 4: Install project dependencies
    - name: Install dependencies
      run: npm install

    # Step 5: Build project (for React, Vue, Angular, etc.)
    - name: Build project
      run: npm run build

    # Step 6: Deploy to Firebase Hosting
    - name: Deploy to Firebase
      run: firebase deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
